SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


INSERT INTO salles VALUES('RDC', 'Lounge', 100);
INSERT INTO salles VALUES('R+1', 'Coworking', 80);
INSERT INTO salles VALUES('R+1', 'Broadcasting', 50);
INSERT INTO salles VALUES('RDC', 'Studio Son', 5);
INSERT INTO salles VALUES('R+1', 'Studio Video', 5);
INSERT INTO salles VALUES('R+1', 'Bocal Peda', 4);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
