SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


INSERT INTO salles VALUES('Lounge', 'RDC');
INSERT INTO salles VALUES('Studio Son', 'RDC');
INSERT INTO salles VALUES('Broadcasting', 'R+1');
INSERT INTO salles VALUES('Bocal Peda', 'R+1');
INSERT INTO salles VALUES('Coworking', 'R+1');
INSERT INTO salles VALUES('Studio Video', 'R+1');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
